<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-E88DK1P" failures="1" tests="2" name="QA" time="24.138" errors="0" timestamp="2022-07-25T08:22:15 IST">
  <testcase classname="script.TestClass1" name="testA" time="0.025"/>
  <testcase classname="script.TestClass2" name="testLogin" time="0.012">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at script.TestClass2.testLogin(TestClass2.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testLogin -->
  <testcase classname="generic.BaseTest" name="@BeforeSuite createReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite createReport -->
  <testcase classname="generic.BaseTest" name="@AfterSuite publishReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite publishReport -->
</testsuite> <!-- QA -->
